name: rtc_s1_sas_final
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.10
  - gdal>=3.0
  - s1reader>=0.2.5
  - numpy>=1.20
  - pybind11>=2.5
  - pyre>=1.11.2
  
  - scipy!=1.10.0
  - isce3==0.24.4
  # Workaround for the issue with `libabseil` (09/11/2023)
  - libabseil=20230125.3